### ISSUE TITLE
RE: please help on how to run

### ISSUE THREAD

**Issue by multilexus** [LokeshPatel/Cordova-Plugin-PrintHandPlugin#1]
Hi Lokesh,

I'm trying to build your code. I'm trying to include your cordova plugin as part of my existing Ionic Framework project and call it, but get errors. Are you able to run and test it? Perhaps you could zip and share your sample test project with brief description how to build and run it and what else is needed to run it? Greatly appreciate it!!!

**Comment by LokeshPatel** [comment]
Thanks for response.
Ok try with ionic framework and update you .

**Comment by LokeshPatel** [comment]
Hi,

I find  the ionic demo code below url, please find.
  https://drive.google.com/open?id=0B0n9QA-gnpAbODBPNk9nemZyQnM

Plugin Method Call in controller.js file like below button event. 

Button first click event for show url for print.

```
  $scope.webUrlShowOnPrintHand = function() {
   var result ="http://www.printHand.com";
   navigator.printhandplugin.printWithHttpURL(function(a){console.log(a)},function(a){console.log(a)},    result);
  }
```

Button Second click show and print contain data page.

```
$scope.printWebPageWithContain = function() {
var printString = "<html><body>ABCD</body></html>";
navigator.printhandplugin.printWebPageWithContain(function(a){console.log(a)},function(a){console.log(a)}, printString);
  }
```

Thanks,
Lokesh Patel

**Comment by multilexus** [comment]
Hello Lokesh,
The good news, your ionic demo works great! 

The problem is, that it still displays print dialog when I click PrintWebPageWithContain button. See attached images: printDialog1 and printDialog2

My goal is to print an html file from my ionic application WITHOUT displaying ANY dialog.That's why I'm using PrintHand
According to https://printhand.com/integration.php page, there're 3 methods to integrate PrintHand
1) Share intent (did you  use this one or number 2 below)2) Intent API (I believe this is what you did)3) Integrate printHand library directly with android application
I believe method #1 will always show preview dialog, however, I believe it should be possible to use method #2 or method #3 without preview dialog.
Could you please take a look and let me know? Thanks, Alex

```
  From: Lokesh Patel <notifications@github.com>
```

 To: LokeshPatel/Cordova-Plugin-PrintHandPlugin Cordova-Plugin-PrintHandPlugin@noreply.github.com 
Cc: multilexus engvibes@yahoo.com
 Sent: Thursday, April 7, 2016 2:15 AM
 Subject: Re: [LokeshPatel/Cordova-Plugin-PrintHandPlugin] RE: please help on how to run (#1)

Hi,I find the ionic demo code below url, please find.
 https://drive.google.com/open?id=0B0n9QA-gnpAbODBPNk9nemZyQnMPlugin Method Call in controller.js file like below button event. Button first click event for show url for print.$scope.webUrlShowOnPrintHand = function() {
 var result ="http://www.printHand.com";
 navigator.printhandplugin.printWithHttpURL(function(a){console.log(a)},function(a){console.log(a)}, result);
 };Button Second click show and print contain data page.$scope.printWebPageWithContain = function() {
var printString = "<html><body>ABCD</body></html>";
navigator.printhandplugin.printWebPageWithContain(function(a){console.log(a)},function(a){console.log(a)}, printString);
  }
Thanks,
Lokesh Patel—

**Comment by LokeshPatel** [comment]
Hi,
Yes, I have implemented only share intent plugins.
Intent API and Service not yet.
Thanks
